name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: ballpoint-lesson
      - name: Build Docker Image
        run: docker build -t ballpoint-lesson ./ballpoint-lesson
      - name: Run Docker Container
        run: |
          docker build -t ballpoint-lesson ./ballpoint-lesson
          docker run --name ballpoint-lesson_container -p 3000:3000 ballpoint-lesson npm run build
          docker cp ballpoint-lesson_container:/usr/src/app/dist ./dist
      - name: Copy build artifacts from container
        run: docker cp ballpoint-lesson_container:/usr/src/app/dist ./dist
      - name: Stop and remove Docker Container
        run: docker rm -f ballpoint-lesson_container
      - name: Check for errors
        run: |
          if [ ! -d "./dist" ]; then
            echo "Build failed! Check the logs for errors."
            exit 1
          fi
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          force_orphan: false
          enable_jekyll: false
          disable_nojekyll: false
          exclude_assets: .github
